### ISSUE TITLE
AuthorizationException  when thread is interrupted

### ISSUE THREAD

**Issue by olayinkasf** [dehora/nakadi-java#224]
For some reason or the other, I always get this exception when I trigger `Ctr + C` on a running Spring context even though the streams are processing events.

```
2017-07-05 19:43:55.755  WARN 6566 --- [-java-compute-0] NakadiClient                             : observer_non_retryable_exception msg=token_assumed_unauthorized; Inferred from invalid response there was an auth issue, see https://github.com/zalando/nakadi/issues/645 raw_response={"error":"unauthorized","error_description":"Full authentication is required to access this resource"} (401)

nakadi.AuthorizationException: token_assumed_unauthorized; Inferred from invalid response there was an auth issue, see https://github.com/zalando/nakadi/issues/645 raw_response={"error":"unauthorized","error_description":"Full authentication is required to access this resource"} (401)
	at nakadi.ProblemSupport.throwProblem(ProblemSupport.java:35) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.OkHttpResource.throwProblem(OkHttpResource.java:316) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.OkHttpResource.handleError(OkHttpResource.java:312) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.OkHttpResource.throwIfError(OkHttpResource.java:297) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:158) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.OkHttpResource.lambda$requestThrowing$3(OkHttpResource.java:106) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.shadow.io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.shadow.io.reactivex.Observable.subscribe(Observable.java:10842) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.shadow.io.reactivex.Observable.blockingFirst(Observable.java:4727) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.OkHttpResource.requestThrowing(OkHttpResource.java:106) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionResourceReal.lambda$checkpoint$3(SubscriptionResourceReal.java:201) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionResourceReal.timed(SubscriptionResourceReal.java:44) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionResourceReal.checkpoint(SubscriptionResourceReal.java:201) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionResourceReal.checkpoint(SubscriptionResourceReal.java:142) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionOffsetCheckpointer.checkpointInner(SubscriptionOffsetCheckpointer.java:117) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionOffsetCheckpointer.checkpointInner(SubscriptionOffsetCheckpointer.java:62) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionOffsetCheckpointer.checkpoint(SubscriptionOffsetCheckpointer.java:52) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionOffsetObserver.checkpoint(SubscriptionOffsetObserver.java:28) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.SubscriptionOffsetObserver.onNext(SubscriptionOffsetObserver.java:21) ~[nakadi-java-client-0.9.0.jar:0.9.0]
	at de.zalando.spoq.nakadijava.JacksonStreamObserver.onNext(JacksonStreamObserver.java:104) ~[nakadi-java-spring-0.3.0.jar:0.3.0]
	at nakadi.StreamBatchRecordSubscriber.onNext(StreamBatchRecordSubscriber.java:59) [nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.StreamBatchRecordSubscriber.onNext(StreamBatchRecordSubscriber.java:10) [nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400) [nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) [nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260) [nakadi-java-client-0.9.0.jar:0.9.0]
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225) [nakadi-java-client-0.9.0.jar:0.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by dehora** [comment]
I can't replicate this. Can you say a bit more about the context this is happening in? The way `token_assumed_unauthorized` happens is when the server refuses a request, which is what's happening in the logs. So far, it's not clear this is a client issue.
