### ISSUE TITLE
Stopping the processor and recreating another one

### ISSUE THREAD

**Issue by olayinkasf** [dehora/nakadi-java#225]
In my use case, I stop the processor when onError is called on the observer and then from another thread I create another processor and start it but I am getting the following exceptions.

The processor are started in different threads.

```
nakadi.shadow.io.reactivex.exceptions.UndeliverableException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@37ffd19 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@449b5109[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at nakadi.shadow.io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at nakadi.shadow.io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:136)
	at nakadi.shadow.io.reactivex.internal.schedulers.ComputationScheduler$EventLoopWorker.schedule(ComputationScheduler.java:211)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutTimedSubscriber.scheduleTimeout(FlowableTimeoutTimed.java:233)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutTimedSubscriber.onNext(FlowableTimeoutTimed.java:223)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:91)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUnsubscribeOn$UnsubscribeSubscriber.onNext(FlowableUnsubscribeOn.java:61)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUsing$UsingSubscriber.onNext(FlowableUsing.java:104)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:91)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:181)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:123)
	at nakadi.shadow.io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onSubscribe(FlowableOnBackpressureBuffer.java:91)
	at nakadi.shadow.io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:49)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer.subscribeActual(FlowableOnBackpressureBuffer.java:46)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:73)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@37ffd19 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@449b5109[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:549)
	at nakadi.shadow.io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:129)
	... 37 more
```

.

```
nakadi.shadow.io.reactivex.exceptions.UndeliverableException: java.io.UncheckedIOException: java.io.InterruptedIOException: thread interrupted
	at nakadi.shadow.io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUnsubscribeOn$UnsubscribeSubscriber.onError(FlowableUnsubscribeOn.java:68)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onError(FlowableSubscribeOn.java:102)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUsing$UsingSubscriber.onError(FlowableUsing.java:124)
	at nakadi.shadow.io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.checkTerminated(FlowableOnBackpressureBuffer.java:225)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:166)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onError(FlowableOnBackpressureBuffer.java:123)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:110)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:194)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:123)
	at nakadi.shadow.io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onSubscribe(FlowableOnBackpressureBuffer.java:91)
	at nakadi.shadow.io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:49)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer.subscribeActual(FlowableOnBackpressureBuffer.java:46)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:73)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.UncheckedIOException: java.io.InterruptedIOException: thread interrupted
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:574)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:191)
	... 23 more
Caused by: java.io.InterruptedIOException: thread interrupted
	at nakadi.shadow.okio.Timeout.throwIfReached(Timeout.java:146)
	at nakadi.shadow.okio.Okio$2.read(Okio.java:135)
	at nakadi.shadow.okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at nakadi.shadow.okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at nakadi.shadow.okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at nakadi.shadow.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:293)
	at nakadi.shadow.okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
	at nakadi.shadow.okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
	at nakadi.shadow.okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at nakadi.shadow.okio.RealBufferedSource.exhausted(RealBufferedSource.java:55)
	at nakadi.shadow.okio.InflaterSource.refill(InflaterSource.java:101)
	at nakadi.shadow.okio.InflaterSource.read(InflaterSource.java:62)
	at nakadi.shadow.okio.GzipSource.read(GzipSource.java:80)
	at nakadi.shadow.okio.RealBufferedSource$1.read(RealBufferedSource.java:429)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at nakadi.shadow.okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:251)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:571)
	... 26 more
```

**Comment by dehora** [comment]
This should be addressed in 0.9.9 which cleans up the output; the exceptions themselves don't stop another processor from starting and are mostly noise.
