### ISSUE TITLE
Infinite retry for 409 Conflict exception.

### ISSUE THREAD

**Issue by satybald** [dehora/nakadi-java#231]
Seem like for the ```Conflict; No free slots for streaming available``` is not able to pick maxRetryAttempts and does Integer.MAX_VALUE attempts. 

```
private val configuration = new StreamConfiguration()
    .maxRetryAttempts(5)
    .subscriptionId(subscriptionId)

val processor = nakadiClient
      .resources()
      .streamBuilder(configuration)
      .streamObserverFactory(new DigaObserverProvider(subscriptionId, bufferService, nakadiClient, offsetService, subscriptionManager))
      .build()
```

In the log
```
I 2017-08-16T13:45:03,161Z NakadiClient nakadi-java-io-0 - retryable_exception_consumer class nakadi.ConflictException Conflict; No free slots for streaming available. Total slots: 1 (409)
nakadi.ConflictException: Conflict; No free slots for streaming available. Total slots: 1 (409)
        at nakadi.ProblemSupport.throwProblem(ProblemSupport.java:44)
        at nakadi.OkHttpResource.throwProblem(OkHttpResource.java:316)
        at nakadi.OkHttpResource.handleError(OkHttpResource.java:312)
        at nakadi.OkHttpResource.throwIfError(OkHttpResource.java:297)
        at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:158)
        at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:167)
        at nakadi.OkHttpResource.lambda$requestThrowing$2(OkHttpResource.java:96)
        at nakadi.shadow.io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32)
        at nakadi.shadow.io.reactivex.Observable.subscribe(Observable.java:10842)
        at nakadi.shadow.io.reactivex.Observable.blockingFirst(Observable.java:4727)
        at nakadi.OkHttpResource.requestThrowing(OkHttpResource.java:96)
        at nakadi.StreamProcessorRequestFactory.requestStreamConnection(StreamProcessorRequestFactory.java:41)
        at nakadi.StreamProcessorRequestFactory.onCall(StreamProcessorRequestFactory.java:33)
        at nakadi.StreamProcessorRequestFactory.lambda$createCallable$0(StreamProcessorRequestFactory.java:21)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:48)
        at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
        at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
        at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
I 2017-08-16T13:45:03,161Z NakadiClient nakadi-java-io-0 - stream_retry_will_sleep sleep=7854 attempt=51/2147483647 thread=nakadi-java-io-0 error=Conflict; No free slots for streaming available. Total slots: 1 (409)
```

**Comment by satybald** [comment]
@dehora I'd highly appreciate if you could give a hint what might cause it.
