### ISSUE TITLE
processor continues streaming even if observer was stopped

### ISSUE THREAD

**Issue by satybald** [dehora/nakadi-java#257]
Nakadi-java client continues streaming even after onStopped and onError method has been called. 

**Expected behavior**: 
client stop streaming and exits gracefully.

**How to reproduce:**
in on onNext method throw IllegalStateException or any Runtime exception.

**Output from the log:**

```
I 2017-09-18T12:25:15,891Z d.zalando.consumer.DigaEventObserver main - OnStart: sub: ddb35c09-7aea-4517-b1b7-13967bb8eb84 
I 2017-09-18T12:25:15,895Z NakadiClient main - **stream_processor has started**
I 2017-09-18T12:25:15,958Z NakadiClient nakadi-java-io-0 - stream_connection_open step=details mode=subscriptionStream url=https://URL:443/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000 scope=nakadi.event_stream.read
I 2017-09-18T12:25:19,017Z NakadiClient nakadi-java-io-0 - stream_connection_open step=opened 733174240 HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,024Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"2","offset":"000000000000001623","event_type":"test2","cursor_token":"916597a0-8d72-4fcd-9bf0-280f58da976c"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:24:57Z","eid":"ae142e56-c3fe-4b1a-aecd-6de94cfe4799","event_type":"test2","partition":"2","received_at":"2017-09-18T12:24:57.429Z","flow_id":"syvvoN68oScq4Lepq4jriDF9","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737497","data_type":"bla","new_field_tracker":"hello world 100"}],"info":{"debug":"Stream started"}}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,041Z NakadiClient nakadi-java-compute-0 - StreamBatchRecordSubscriber.onNext
D 2017-09-18T12:25:19,042Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"2","offset":"000000000000001624","event_type":"test2","cursor_token":"242b389b-f962-4fa9-a760-99d1a18431cd"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:24:57Z","eid":"e35175b4-948e-466f-bc28-05d7040ddb1a","event_type":"test2","partition":"2","received_at":"2017-09-18T12:24:58.125Z","flow_id":"EoFQslljEXUUB0iDYPDI0drC","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737497","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,042Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"1","offset":"000000000000001666","event_type":"test2","cursor_token":"24e58813-a6f4-423c-8ec5-dc05c472f2b5"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:24:56Z","eid":"a5f2392e-8030-45e1-828a-ea3daaaa1c50","event_type":"test2","partition":"1","received_at":"2017-09-18T12:24:56.772Z","flow_id":"fju0IkHgLalg7lIrsbiwDWyw","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737496","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,043Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"1","offset":"000000000000001667","event_type":"test2","cursor_token":"bd5f5413-f9e1-4415-af26-830de6b4e4bd"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:00Z","eid":"bb726d3d-5796-4cda-b8af-08508db834fe","event_type":"test2","partition":"1","received_at":"2017-09-18T12:25:00.917Z","flow_id":"O2DDUPwjjxHQXrxbBCwJi2oX","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737500","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,044Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"1","offset":"000000000000001668","event_type":"test2","cursor_token":"15785782-e91c-4e7b-81fd-a8230c3cddcc"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:01Z","eid":"8300812d-c8da-4a1d-a55c-1dd735f3fe89","event_type":"test2","partition":"1","received_at":"2017-09-18T12:25:01.617Z","flow_id":"7KsLp2By2F4ixls65JIOkB9w","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737501","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,044Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"1","offset":"000000000000001669","event_type":"test2","cursor_token":"5a7888a2-96be-4db2-9b8c-9de3a3fbb4b8"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:02Z","eid":"3521b5cc-3e84-4026-9ea8-07d52af033a9","event_type":"test2","partition":"1","received_at":"2017-09-18T12:25:02.317Z","flow_id":"SWBaIMzNDvSDTp1Oi02DdoFN","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737502","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,045Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"1","offset":"000000000000001670","event_type":"test2","cursor_token":"839a94fe-deaa-460d-902f-b345c76a3e94"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:02Z","eid":"a4f9a019-60a1-4014-a001-0aaa51df8abd","event_type":"test2","partition":"1","received_at":"2017-09-18T12:25:03.013Z","flow_id":"sP8hlKqrQH4KCSRaED8bsOJA","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737502","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
W 2017-09-18T12:25:19,045Z NakadiClient nakadi-java-compute-0 - observer_non_retryable_exception msg=Redis offset
java.lang.IllegalStateException: Redis offset
	at de.zalando.consumer.DigaEventObserver$$anonfun$stopConsumingSubscription$1.applyOrElse(DigaEventObserver.scala:95)
	at de.zalando.consumer.DigaEventObserver$$anonfun$stopConsumingSubscription$1.applyOrElse(DigaEventObserver.scala:93)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at de.zalando.consumer.DigaEventObserver.onNext(DigaEventObserver.scala:54)
	at nakadi.StreamBatchRecordSubscriber.onNext(StreamBatchRecordSubscriber.java:59)
	at nakadi.StreamBatchRecordSubscriber.onNext(StreamBatchRecordSubscriber.java:10)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
I 2017-09-18T12:25:19,046Z d.zalando.consumer.DigaEventObserver nakadi-java-compute-0 - Stopped Observer: ddb35c09-7aea-4517-b1b7-13967bb8eb84
D 2017-09-18T12:25:19,047Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"3","offset":"000000000000001652","event_type":"test2","cursor_token":"6d776f2d-4c91-4983-92c3-5dd111764858"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:24:55Z","eid":"60ffc46c-7660-4877-bc79-99fa31ba25b3","event_type":"test2","partition":"3","received_at":"2017-09-18T12:24:56.093Z","flow_id":"0HiR03XT55Q6yNUdfA6RMI1R","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737495","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,048Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"3","offset":"000000000000001653","event_type":"test2","cursor_token":"0bc5ac28-3576-4aaa-9cd0-6b99bcc372f3"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:24:58Z","eid":"870c8c22-01d0-494c-b1f9-3cf2dbb9fbbf","event_type":"test2","partition":"3","received_at":"2017-09-18T12:24:58.792Z","flow_id":"aBahPRSsA9G85CQHEJRi2qsv","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737498","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,049Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"3","offset":"000000000000001654","event_type":"test2","cursor_token":"b0f64f4b-2d37-47ec-8744-c62547a2915b"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:24:59Z","eid":"3c053ec9-8fac-4489-bb98-d8f80e348af7","event_type":"test2","partition":"3","received_at":"2017-09-18T12:24:59.440Z","flow_id":"perh4Y7NiAfVDc53RBdpphPm","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737499","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:19,050Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"3","offset":"000000000000001655","event_type":"test2","cursor_token":"7547e097-fce9-4976-8ac7-9dec904e2c59"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:24:59Z","eid":"86b3f80f-da9f-4430-8785-826b339dda1c","event_type":"test2","partition":"3","received_at":"2017-09-18T12:25:00.152Z","flow_id":"BUVUfn5pkFSN9GRsVnqivcUw","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737499","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
I 2017-09-18T12:25:19,050Z NakadiClient nakadi-java-compute-0 - StreamBatchRecordSubscriber.onError Redis offset
E 2017-09-18T12:25:19,051Z d.zalando.consumer.DigaEventObserver nakadi-java-compute-0 - Error processing stream sub: ddb35c09-7aea-4517-b1b7-13967bb8eb84 msg: Redis offset
java.lang.IllegalStateException: Redis offset
	at de.zalando.consumer.DigaEventObserver$$anonfun$stopConsumingSubscription$1.applyOrElse(DigaEventObserver.scala:95)
	at de.zalando.consumer.DigaEventObserver$$anonfun$stopConsumingSubscription$1.applyOrElse(DigaEventObserver.scala:93)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at de.zalando.consumer.DigaEventObserver.onNext(DigaEventObserver.scala:54)
	at nakadi.StreamBatchRecordSubscriber.onNext(StreamBatchRecordSubscriber.java:59)
	at nakadi.StreamBatchRecordSubscriber.onNext(StreamBatchRecordSubscriber.java:10)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
D 2017-09-18T12:25:37,827Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"0","offset":"000000000000001606","event_type":"test2","cursor_token":"9a9f23b6-0d24-4dd3-8124-b1c36069f20a"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:37Z","eid":"2bd74043-68a8-4acf-8443-09056dccd810","event_type":"test2","partition":"0","received_at":"2017-09-18T12:25:37.808Z","flow_id":"ZJ0AAtyliQepbAZhFNOHiF93","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737537","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:39,095Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"3","offset":"000000000000001656","event_type":"test2","cursor_token":"29bdd364-7b29-4bb2-8295-658f1448a2c7"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:38Z","eid":"d1beba84-fa0a-4f43-9850-6f598e7df211","event_type":"test2","partition":"3","received_at":"2017-09-18T12:25:39.081Z","flow_id":"vu8M60OeZU9UxJY4F92Nl90a","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737538","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://URL/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:41,293Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"0","offset":"000000000000001607","event_type":"test2","cursor_token":"4286c089-9248-4a98-a8a2-903b6d66e274"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:41Z","eid":"d73c13f5-c492-42ec-b493-99762beeb7e1","event_type":"test2","partition":"0","received_at":"2017-09-18T12:25:41.274Z","flow_id":"iaJ1G15mRFUxZY8GvNhXTD7j","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737541","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://nakadi-staging.aruha-test.zalan.do/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:42,402Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"1","offset":"000000000000001671","event_type":"test2","cursor_token":"fab78fb0-8249-40dc-b000-25b3022b59fc"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:42Z","eid":"3bb19558-4a1a-4703-a8ba-315b2c474bd7","event_type":"test2","partition":"1","received_at":"2017-09-18T12:25:42.387Z","flow_id":"VZskiK2a18nCfRDuf9RTzFng","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737542","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://nakadi-staging.aruha-test.zalan.do/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:43,348Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"3","offset":"000000000000001658","event_type":"test2","cursor_token":"a674d055-19c5-451b-8f6c-2124c50e484a"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:43Z","eid":"21ff3eb3-8bc9-402e-ac15-3cc78c66f338","event_type":"test2","partition":"3","received_at":"2017-09-18T12:25:43.334Z","flow_id":"MyYl5f8jRX1NmWxikRmfwubh","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737543","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://nakadi-staging.aruha-test.zalan.do/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:44,057Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"0","offset":"000000000000001608","event_type":"test2","cursor_token":"1c938264-7be3-4f63-a0f6-38b21b7e3841"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:43Z","eid":"55b3d551-68bf-4748-ae3d-bf56cfd88c7a","event_type":"test2","partition":"0","received_at":"2017-09-18T12:25:44.039Z","flow_id":"PSfiq0mztwL95oIkIMZf7HRB","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737543","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://nakadi-staging.aruha-test.zalan.do/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:44,784Z NakadiClient nakadi-java-io-0 - tokenized line from stream {"cursor":{"partition":"2","offset":"000000000000001625","event_type":"test2","cursor_token":"0f36a8f3-6146-42db-955f-7bae0178604c"},"events":[{"metadata":{"occurred_at":"2017-09-18T12:25:44Z","eid":"613dee3d-1f7f-496e-b3d7-416c642b2244","event_type":"test2","partition":"2","received_at":"2017-09-18T12:25:44.768Z","flow_id":"0QuqNVKuwgakyziJkzp9Mpwj","version":"1.0.0"},"data_op":"C","data":{"key1":"value1","key2":"value2"},"order_number":"1505737544","data_type":"bla","new_field_tracker":"hello world 100"}]}, HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=https://nakadi-staging.aruha-test.zalan.do/subscriptions/ddb35c09-7aea-4517-b1b7-13967bb8eb84/events?max_uncommitted_events=1000000000}}
D 2017-09-18T12:25:45,653Z NakadiClient nakadi-java-io-0 - tokenized line fr
```

**Comment by dehora** [comment]
> in on onNext method throw IllegalStateException or any Runtime exception.

This should be address in 0.9.6 and up. https://github.com/dehora/nakadi-java/pull/261 has a test case specifically for IllegalStateException which will now stop a processor.
