### ISSUE TITLE
OkHTTP Thread pool leak when incorrect processor config is supplied

### ISSUE THREAD

**Issue by satybald** [dehora/nakadi-java#284]
Whenever an incorrect or malformed processor config is supplied. Seems like under the hood the library is not shutting OKHttp pool and leaving a bunch of CLOSE_WAIT TCP connections.

**How to reproduce**
```
  while (true) {
    findSubscriptoinsAndStartProcessor()
    Thread.sleep(1000)
  }

Config for processor
.maxRetryDelay(100, TimeUnit.MILLISECONDS)
```

Processor throws an error and leaving a bunch of OkHTTP threads in waiting  state and TCP sockets in TIMED_WAIT.
```
Error starting consumer supplied max delay cannot be less than 1s for subscription Subscription
```
Library version: 0.9.11
Number of open TCP sockets that belongs to application
```
netstat -antp  |grep 931/java |grep CLOSE_WAIT | wc -l
201
```
Thread graph: 
![image](https://user-images.githubusercontent.com/2764630/31189403-72fec864-a938-11e7-99aa-9d50178a068e.png)

![image](https://user-images.githubusercontent.com/2764630/31189474-a582044a-a938-11e7-9c50-ec129f29b357.png)

**Comment by dehora** [comment]
> Whenever an incorrect or malformed processor config is 
> supplied. Seems like under the hood the library is not 
> shutting OKHttp pool and leaving a bunch of 
> CLOSE_WAIT TCP connections.
>
> How to reproduce
>
>```
>  while (true) {
>    findSubscriptoinsAndStartProcessor()
>   Thread.sleep(1000)
> }
>
>Config for processor
>.maxRetryDelay(100, TimeUnit.MILLISECONDS)
>

Can  you say a bit more about the `findSubscriptoinsAndStartProcessor` code? I doubt this

```java
.maxRetryDelay(100, TimeUnit.MILLISECONDS)
```

is causing the issue the you're seeing as that will throw an exception immediately when set and not when the the processor is started. As an example, this:

```java
    NakadiClient client = NakadiClient.newBuilder()
        .baseURI(baseUri())
        .certificatePath("classpath:certs")
        .tokenProvider(scope -> Optional.of("Bearer " + token()))
        .build();

    final SubscriptionOffsetCheckpointer checkpointer =
        new SubscriptionOffsetCheckpointer(client)
            .suppressInvalidSessionException(true)
            .suppressNetworkException(true);

    while (true) {
      
      StreamConfiguration sc = new StreamConfiguration()
          .subscriptionId(subscriptionId())
          .maxRetryDelay(500, TimeUnit.MILLISECONDS);

      StreamProcessor processor = client.resources()
          .streamBuilder(sc)
          .checkpointer(checkpointer)
          .streamObserverFactory(streamObserverProvider("processor"))
          .build();

      processor.start();
      logger.info("processor started in background");
      Thread.sleep(1_000L);
    }
```

will crash immediately and not get to the processor;

```

20:07:03.060 [main] INFO NakadiClient - Loaded metric collector nakadi.MetricCollectorDevnull
Exception in thread "main" java.lang.IllegalArgumentException: supplied max delay cannot be less than 1s
	at nakadi.StreamConfiguration.maxRetryDelay(StreamConfiguration.java:234)
	at nakadi.SpikeMain284.main(SpikeMain284.java:31)

Process finished with exit code 1
```

**Comment by dehora** [comment]
I'm retitling this to look at `maxRetryAttempts` which I think is the underlying issue.

**Comment by PetrGlad** [comment]
I wonder why OkHttp would use so many (waiting!) threads. 
In documentation it is described as using NIO, only place I find "pool" or executor is in MockWebServer class.
