### ISSUE TITLE
Http status 404 gets translated into 500

### ISSUE THREAD

**Issue by kanuku** [dehora/nakadi-java#296]
Hi,

When using the `tryFindByName` , the Nakadi server returns a 404, but the client throws a ServerException with a 500... 

### Nakadi logs
```
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : --> GET http://localhost:8080/event-types/wolf.template-engine.dev.DE.ZALANDO.LOGISTICS.ALE.CHAIN_PATCH_OUTBOUND_PROCESS_CREATION.ver_1 http/1.1
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : Accept-Charset: UTF-8
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : X-Client-Platform-Details: {}
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : Accept: application/json
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : User-Agent: nakadi-java/0.9.5
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : X-Flow-Id: njc-1507626082993-7d061416009a81fd
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : Authorization: ********
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : Host: localhost:8080
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : Connection: Keep-Alive
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : Accept-Encoding: gzip
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : --> END GET
2017-10-10 11:01:23.700  INFO 1805 --- [           main] NakadiClientHttpLog                      : <-- 500 Server Error http://localhost:8080/event-types/wolf.template-engine.dev.DE.ZALANDO.LOGISTICS.ALE.CHAIN_PATCH_OUTBOUND_PROCESS_CREATION.ver_1 (515ms)
2017-10-10 11:01:23.700  INFO 1805 --- [           main] NakadiClientHttpLog                      : Content-Type: application/json;charset=utf-8
2017-10-10 11:01:23.700  INFO 1805 --- [           main] NakadiClientHttpLog                      : Connection: close
2017-10-10 11:01:23.702  INFO 1805 --- [           main] NakadiClientHttpLog                      :
2017-10-10 11:01:23.702  INFO 1805 --- [           main] NakadiClientHttpLog                      : {"timestamp":"2017-10-10T09:01:23.694+0000","status":500,"error":"Internal Server Error","exception":"org.springframework.web.client.HttpClientErrorException","message":"org.springframework.web.client.HttpClientErrorException: 404 Not Found","path":"/event-types/wolf.template-engine.dev.DE.ZALANDO.LOGISTICS.ALE.CHAIN_PATCH_OUTBOUND_PROCESS_CREATION.ver_1"}
2017-10-10 11:01:23.703  INFO 1805 --- [           main] NakadiClientHttpLog                      : <-- END HTTP (358-byte body)
2017-10-10 11:01:23.724  WARN 1805 --- [           main] d.z.a.p.n.hla.NakadiClientWrapperImpl    : ServerException - http-status: 500 - reason: null;  (500)
2017-10-10 11:01:23.727  INFO 1805 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-10-10 11:01:23.746 ERROR 1805 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at de.zalando.ale.processtemplateengine.ProcessTemplateEngineApplication.main(ProcessTemplateEngineApplication.java:16) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506) [spring-boot-maven-plugin-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: nakadi.ServerException: null;  (500)
	at nakadi.ProblemSupport.throwProblem(ProblemSupport.java:63) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.throwProblem(OkHttpResource.java:316) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.handleError(OkHttpResource.java:312) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.throwIfError(OkHttpResource.java:297) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:158) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:167) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.lambda$requestThrowing$5(OkHttpResource.java:124) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.shadow.io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.shadow.io.reactivex.Observable.subscribe(Observable.java:10842) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.shadow.io.reactivex.Observable.blockingFirst(Observable.java:4727) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.requestThrowing(OkHttpResource.java:124) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.EventTypeResourceReal.findByName(EventTypeResourceReal.java:83) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.EventTypeResourceReal.tryFindByName(EventTypeResourceReal.java:90) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at de.zalando.ale.processtemplateengine.nakadi.hla.NakadiClientWrapperImpl.eventTypeExists(NakadiClientWrapperImpl.java:150) ~[classes/:na]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.subscribe(NakadiSubscriptionInitializer.java:143) ~[classes/:na]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.lambda$null$2(NakadiSubscriptionInitializer.java:120) ~[classes/:na]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_144]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.lambda$initializeNakadiSubscriptions$3(NakadiSubscriptionInitializer.java:111) ~[classes/:na]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_144]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_144]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.initializeNakadiSubscriptions(NakadiSubscriptionInitializer.java:105) ~[classes/:na]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.run(NakadiSubscriptionInitializer.java:68) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	... 12 common frames omitted

2017-10-10 11:01:23.750  INFO 1805 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1109b6e: startup date [Tue Oct 10 11:01:15 CEST 2017]; root of context hierarchy
2017-10-10 11:01:23.760  INFO 1805 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2017-10-10 11:01:23.762  INFO 1805 --- [           main] o.zalando.stups.tokens.AccessTokensBean  : Stop 'accessTokenRefresher' ...
2017-10-10 11:01:23.764  INFO 1805 --- [           main] o.zalando.stups.tokens.AccessTokensBean  : 'accessTokenRefresher' stopped.
2017-10-10 11:01:23.766  INFO 1805 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-10-10 11:01:23.767  INFO 1805 --- [           main] .a.p.n.h.u.NakadiSubscriptionInitializer : There are 0 subscriptions to be stopped!
[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at de.zalando.ale.processtemplateengine.ProcessTemplateEngineApplication.main(ProcessTemplateEngineApplication.java:16)
	... 6 more
Caused by: nakadi.ServerException: null;  (500)
	at nakadi.ProblemSupport.throwProblem(ProblemSupport.java:63)
	at nakadi.OkHttpResource.throwProblem(OkHttpResource.java:316)
	at nakadi.OkHttpResource.handleError(OkHttpResource.java:312)
	at nakadi.OkHttpResource.throwIfError(OkHttpResource.java:297)
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:158)
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:167)
	at nakadi.OkHttpResource.lambda$requestThrowing$5(OkHttpResource.java:124)
	at nakadi.shadow.io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32)
	at nakadi.shadow.io.reactivex.Observable.subscribe(Observable.java:10842)
	at nakadi.shadow.io.reactivex.Observable.blockingFirst(Observable.java:4727)
	at nakadi.OkHttpResource.requestThrowing(OkHttpResource.java:124)
	at nakadi.EventTypeResourceReal.findByName(EventTypeResourceReal.java:83)
	at nakadi.EventTypeResourceReal.tryFindByName(EventTypeResourceReal.java:90)
	at de.zalando.ale.processtemplateengine.nakadi.hla.NakadiClientWrapperImpl.eventTypeExists(NakadiClientWrapperImpl.java:150)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.subscribe(NakadiSubscriptionInitializer.java:143)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.lambda$null$2(NakadiSubscriptionInitializer.java:120)
	at java.util.Optional.ifPresent(Optional.java:159)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.lambda$initializeNakadiSubscriptions$3(NakadiSubscriptionInitializer.java:111)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.initializeNakadiSubscriptions(NakadiSubscriptionInitializer.java:105)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.run(NakadiSubscriptionInitializer.java:68)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	... 12 more
```

### Client logs
```
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : --> GET http://localhost:8080/event-types/wolf.template-engine.dev.DE.ZALANDO.LOGISTICS.ALE.CHAIN_PATCH_OUTBOUND_PROCESS_CREATION.ver_1 http/1.1
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : Accept-Charset: UTF-8
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : X-Client-Platform-Details: {}
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : Accept: application/json
2017-10-10 11:01:23.182  INFO 1805 --- [           main] NakadiClientHttpLog                      : User-Agent: nakadi-java/0.9.5
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : X-Flow-Id: njc-1507626082993-7d061416009a81fd
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : Authorization: ********
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : Host: localhost:8080
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : Connection: Keep-Alive
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : Accept-Encoding: gzip
2017-10-10 11:01:23.184  INFO 1805 --- [           main] NakadiClientHttpLog                      : --> END GET
2017-10-10 11:01:23.700  INFO 1805 --- [           main] NakadiClientHttpLog                      : <-- 500 Server Error http://localhost:8080/event-types/wolf.template-engine.dev.DE.ZALANDO.LOGISTICS.ALE.CHAIN_PATCH_OUTBOUND_PROCESS_CREATION.ver_1 (515ms)
2017-10-10 11:01:23.700  INFO 1805 --- [           main] NakadiClientHttpLog                      : Content-Type: application/json;charset=utf-8
2017-10-10 11:01:23.700  INFO 1805 --- [           main] NakadiClientHttpLog                      : Connection: close
2017-10-10 11:01:23.702  INFO 1805 --- [           main] NakadiClientHttpLog                      :
2017-10-10 11:01:23.702  INFO 1805 --- [           main] NakadiClientHttpLog                      : {"timestamp":"2017-10-10T09:01:23.694+0000","status":500,"error":"Internal Server Error","exception":"org.springframework.web.client.HttpClientErrorException","message":"org.springframework.web.client.HttpClientErrorException: 404 Not Found","path":"/event-types/wolf.template-engine.dev.DE.ZALANDO.LOGISTICS.ALE.CHAIN_PATCH_OUTBOUND_PROCESS_CREATION.ver_1"}
2017-10-10 11:01:23.703  INFO 1805 --- [           main] NakadiClientHttpLog                      : <-- END HTTP (358-byte body)
2017-10-10 11:01:23.724  WARN 1805 --- [           main] d.z.a.p.n.hla.NakadiClientWrapperImpl    : ServerException - http-status: 500 - reason: null;  (500)
2017-10-10 11:01:23.727  INFO 1805 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-10-10 11:01:23.746 ERROR 1805 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at de.zalando.ale.processtemplateengine.ProcessTemplateEngineApplication.main(ProcessTemplateEngineApplication.java:16) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506) [spring-boot-maven-plugin-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: nakadi.ServerException: null;  (500)
	at nakadi.ProblemSupport.throwProblem(ProblemSupport.java:63) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.throwProblem(OkHttpResource.java:316) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.handleError(OkHttpResource.java:312) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.throwIfError(OkHttpResource.java:297) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:158) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:167) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.lambda$requestThrowing$5(OkHttpResource.java:124) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.shadow.io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.shadow.io.reactivex.Observable.subscribe(Observable.java:10842) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.shadow.io.reactivex.Observable.blockingFirst(Observable.java:4727) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.OkHttpResource.requestThrowing(OkHttpResource.java:124) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.EventTypeResourceReal.findByName(EventTypeResourceReal.java:83) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at nakadi.EventTypeResourceReal.tryFindByName(EventTypeResourceReal.java:90) ~[nakadi-java-client-0.9.5.jar:0.9.5]
	at de.zalando.ale.processtemplateengine.nakadi.hla.NakadiClientWrapperImpl.eventTypeExists(NakadiClientWrapperImpl.java:150) ~[classes/:na]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.subscribe(NakadiSubscriptionInitializer.java:143) ~[classes/:na]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.lambda$null$2(NakadiSubscriptionInitializer.java:120) ~[classes/:na]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_144]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.lambda$initializeNakadiSubscriptions$3(NakadiSubscriptionInitializer.java:111) ~[classes/:na]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_144]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_144]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.initializeNakadiSubscriptions(NakadiSubscriptionInitializer.java:105) ~[classes/:na]
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.run(NakadiSubscriptionInitializer.java:68) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
	... 12 common frames omitted

2017-10-10 11:01:23.750  INFO 1805 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1109b6e: startup date [Tue Oct 10 11:01:15 CEST 2017]; root of context hierarchy
2017-10-10 11:01:23.760  INFO 1805 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2017-10-10 11:01:23.762  INFO 1805 --- [           main] o.zalando.stups.tokens.AccessTokensBean  : Stop 'accessTokenRefresher' ...
2017-10-10 11:01:23.764  INFO 1805 --- [           main] o.zalando.stups.tokens.AccessTokensBean  : 'accessTokenRefresher' stopped.
2017-10-10 11:01:23.766  INFO 1805 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-10-10 11:01:23.767  INFO 1805 --- [           main] .a.p.n.h.u.NakadiSubscriptionInitializer : There are 0 subscriptions to be stopped!
[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at de.zalando.ale.processtemplateengine.ProcessTemplateEngineApplication.main(ProcessTemplateEngineApplication.java:16)
	... 6 more
Caused by: nakadi.ServerException: null;  (500)
	at nakadi.ProblemSupport.throwProblem(ProblemSupport.java:63)
	at nakadi.OkHttpResource.throwProblem(OkHttpResource.java:316)
	at nakadi.OkHttpResource.handleError(OkHttpResource.java:312)
	at nakadi.OkHttpResource.throwIfError(OkHttpResource.java:297)
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:158)
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:167)
	at nakadi.OkHttpResource.lambda$requestThrowing$5(OkHttpResource.java:124)
	at nakadi.shadow.io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32)
	at nakadi.shadow.io.reactivex.Observable.subscribe(Observable.java:10842)
	at nakadi.shadow.io.reactivex.Observable.blockingFirst(Observable.java:4727)
	at nakadi.OkHttpResource.requestThrowing(OkHttpResource.java:124)
	at nakadi.EventTypeResourceReal.findByName(EventTypeResourceReal.java:83)
	at nakadi.EventTypeResourceReal.tryFindByName(EventTypeResourceReal.java:90)
	at de.zalando.ale.processtemplateengine.nakadi.hla.NakadiClientWrapperImpl.eventTypeExists(NakadiClientWrapperImpl.java:150)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.subscribe(NakadiSubscriptionInitializer.java:143)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.lambda$null$2(NakadiSubscriptionInitializer.java:120)
	at java.util.Optional.ifPresent(Optional.java:159)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.lambda$initializeNakadiSubscriptions$3(NakadiSubscriptionInitializer.java:111)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.initializeNakadiSubscriptions(NakadiSubscriptionInitializer.java:105)
	at de.zalando.ale.processtemplateengine.nakadi.hla.util.NakadiSubscriptionInitializer.run(NakadiSubscriptionInitializer.java:68)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	... 12 more
```

**Comment by dehora** [comment]
@kanuku I can't replicate this - on the current master `tryFindByName` returns Optional.empty and `findByName` throws a `NotFoundException`. What version are you using?

**Comment by dehora** [comment]
Closing for now, as it's not replicating in recent versions.

**Comment by kanuku** [comment]
@dehora It can be replicated by running the `tryFindByName` against an empty nakadi server.
When there are no eventTypes to be returned, nakadi clearly returns 404 and the client throws an exception with status 500...  
 It is not critical, we stopped using using the `tryFindByName` method.
